"""Migracao Inicial

Revision ID: bfc4c9da586a
Revises: 
Create Date: 2026-02-10 16:53:36.021077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc4c9da586a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamados',
    sa.Column('idChamados', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ocorrencias', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('idChamados')
    )
    op.create_table('clientes',
    sa.Column('idClientes', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomeClientes', sa.String(length=150), nullable=True),
    sa.Column('cnpnj', sa.String(length=14), nullable=True),
    sa.Column('contrato', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('idClientes')
    )
    op.create_table('usuarios',
    sa.Column('idUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomeUsuario', sa.String(length=150), nullable=True),
    sa.Column('emailUsuario', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idUsuario')
    )
    op.create_table('alertas',
    sa.Column('idAlertas', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente', sa.Integer(), nullable=True),
    sa.Column('nomeAlerta', sa.String(length=300), nullable=True),
    sa.Column('plataforma', sa.String(length=150), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('critical', sa.Text(), nullable=True),
    sa.Column('unknown', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente'], ['clientes.idClientes'], ),
    sa.PrimaryKeyConstraint('idAlertas')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertas')
    op.drop_table('usuarios')
    op.drop_table('clientes')
    op.drop_table('chamados')
    # ### end Alembic commands ###
